#!/usr/bin/env python3
"""
Generate Terraform tfvars files from the Toggle Registry.

This script reads the toggle-registry.yaml and generates stacks.auto.tfvars files
for each environment based on stack toggle configurations.
"""

import yaml
import os
import sys
from pathlib import Path
from typing import Dict, Any


def load_toggle_registry(registry_path: Path) -> Dict[str, Any]:
    """Load the toggle registry YAML file."""
    try:
        with open(registry_path, 'r') as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        print(f"Error: Toggle registry file not found: {registry_path}", file=sys.stderr)
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"Error parsing toggle registry YAML: {str(e)}", file=sys.stderr)
        sys.exit(1)


def generate_stack_tfvars(stack_toggles: list, environment: str) -> str:
    """Generate tfvars content for a specific environment."""
    
    tfvars_lines = [
        "# Auto-generated from toggle-registry.yaml",
        "# DO NOT EDIT THIS FILE MANUALLY",
        f"# Environment: {environment}",
        ""
    ]
    
    for toggle in stack_toggles:
        toggle_id = toggle.get('id', '')
        terraform_var = toggle.get('terraform_variable', '')
        env_values = toggle.get('environments', {})
        
        if terraform_var and environment in env_values:
            value = 'true' if env_values[environment] else 'false'
            tfvars_lines.append(f"{terraform_var} = {value}")
    
    return '\n'.join(tfvars_lines) + '\n'


def write_tfvars_file(output_file: Path, content: str) -> None:
    """Write the tfvars content to the specified output file path."""
    try:
        # Ensure the output directory exists
        output_file.parent.mkdir(parents=True, exist_ok=True)
    

        with open(output_file, 'w') as f:
            f.write(content)

        print(f"Generated: {output_file}", file=sys.stderr)
    except IOError as e:
        print(f"Error writing tfvars file: {str(e)}", file=sys.stderr)
        sys.exit(1)


def generate_stack_toggles(
    registry_file: str, environment: str, environments_dir: str, dry_run: bool = False
) -> str:
    """
    Main function to generate stack toggles tfvars.

    Args:
        registry_file: Path to the toggle registry YAML file
        environment: The environment to generate toggles for
        environments_dir: Path to the environments directory
        dry_run: If True, print content without writing files

    Returns:
        Path to the generated tfvars file
    """
    try:
        print(f"Loading toggle registry from: {registry_file}", file=sys.stderr)
        print(f"Generating stack toggles for environment: {environment}", file=sys.stderr)

        registry_path = Path(registry_file)
        toggles_dir = Path(environments_dir)

        # Validate registry file exists
        if not registry_path.exists():
            print(f"Error: Toggle registry not found at {registry_path}", file=sys.stderr)
            sys.exit(1)

        # Load toggle registry
        toggle_registry = load_toggle_registry(registry_path)

        # Get list of stack toggles
        stack_toggles = toggle_registry.get('stack_toggles', [])
        if not stack_toggles:
            print("No stack_toggles found in registry; nothing to generate", file=sys.stderr)
            sys.exit(0)

        # Validate required fields for each toggle
        required_fields = [
            'id',
            'name',
            'description',
            'terraform_variable',
            'stack_path',
            'owner',
            'environments',
        ]

        validation_errors = []
        for idx, toggle in enumerate(stack_toggles):
            missing = [f for f in required_fields if f not in toggle]
            if missing:
                ident = toggle.get('id', f'index {idx}')
                validation_errors.append(
                    f"Toggle '{ident}' missing required fields: {', '.join(missing)}"
                )
                continue

            # Basic type/content checks
            if not isinstance(toggle.get('environments'), dict):
                ident = toggle.get('id', f'index {idx}')
                validation_errors.append(
                    f"Toggle '{ident}' has invalid 'environments' (expected object/dict)"
                )

            for key in ['id', 'name', 'description', 'terraform_variable', 'stack_path', 'owner']:
                val = toggle.get(key)
                if not isinstance(val, str) or not val.strip():
                    ident = toggle.get('id', f'index {idx}')
                    validation_errors.append(
                        f"Toggle '{ident}' has invalid '{key}' (expected non-empty string)"
                    )

        if validation_errors:
            print("Error: Found validation issues in stack_toggles", file=sys.stderr)
            for err in validation_errors:
                print(f"- {err}", file=sys.stderr)
            sys.exit(1)

        # Extract all unique environments from the toggle registry
        all_environments = set()
        for toggle in stack_toggles:
            env_values = toggle.get('environments', {})
            all_environments.update(env_values.keys())

        # Validate environment exists in registry
        if environment not in all_environments:
            print(f"Error: Environment '{environment}' not found in toggle registry", file=sys.stderr)
            print(f"Available environments: {', '.join(sorted(all_environments))}", file=sys.stderr)
            sys.exit(1)

        # Determine output file path within toggles directory
        output_path = toggles_dir / f"stacks.{environment}.auto.tfvars"

        # Determine if any toggles apply for this environment
        assignment_count = sum(
            1 for t in stack_toggles
            if t.get('terraform_variable') and environment in t.get('environments', {})
        )

        if assignment_count == 0:
            msg = (
                f"No stack toggle assignments for environment '{environment}'; "
                f"skipping file creation in {toggles_dir}"
            )
            if dry_run:
                print(f"\n--- {output_path.name} (dry run) ---")
                print("# No stack toggles defined for this environment\n")
                print(msg)
                return "(dry-run mode)"
            else:
                print(msg, file=sys.stderr)
                return ""

        # Generate tfvars content
        tfvars_content = generate_stack_tfvars(stack_toggles, environment)

        if dry_run:
            print(f"\n--- {output_path.name} ---")
            print(tfvars_content)
            return "(dry-run mode)"
        else:
            write_tfvars_file(output_path, tfvars_content)
            print(f"Stack toggles tfvars written to: {output_path}", file=sys.stderr)
            return str(output_path)

    except Exception as e:
        print(f"Error generating stack toggles: {str(e)}", file=sys.stderr)
        sys.exit(1)


def main():
    """Entry point when script is run directly."""
    # Read environment variables
    environment = os.environ.get("ENVIRONMENT")
    registry_file = os.environ.get("TOGGLE_REGISTRY_FILE")
    toggle_dir = os.environ.get("TOGGLE_DIR")
    dry_run = os.environ.get("DRY_RUN", "").lower() in ("true", "1", "yes")

    # Validate required environment variables
    if not environment:
        print("Error: ENVIRONMENT environment variable is required", file=sys.stderr)
        sys.exit(1)

    if not registry_file:
        print("Error: TOGGLE_REGISTRY_FILE environment variable is required", file=sys.stderr)
        sys.exit(1)

    if not toggle_dir:
        print("Error: TOGGLE_DIR environment variable is required", file=sys.stderr)
        sys.exit(1)

    # Generate the stack toggles
    generated_file = generate_stack_toggles(
        registry_file, environment, toggle_dir, dry_run
    )
    print(generated_file)


if __name__ == '__main__':
    main()
