name: "Service automation APIM tests action"
description: "Run service automation tests for APIM endpoints"

inputs:
  environment:
    description: "The name of the environment to action the infrastructure"
    required: true
  workspace:
    description: "The name of the workspace to action the infrastructure into."
    required: true
  aws_region:
    description: "AWS region"
    required: true
  api_name:
    description: "API name to test (e.g., dos-search)"
    required: true
  apim_env:
    description: "APIM environment (e.g., internal-dev, internal-qa)"
    required: true
  commit_hash:
    description: "The commit hash, set by the CI/CD pipeline workflow"
    required: false
  tag:
    description: "The tag to build and deploy from"
    required: false

runs:
  using: "composite"
  steps:
    - name: Run service automation APIM tests script
      id: run-service-automation-apim-tests-script
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws_region }}
        WORKSPACE: ${{ inputs.workspace }}
        ENVIRONMENT: ${{ inputs.environment }}
        API_NAME: ${{ inputs.api_name }}
        APIM_ENV: ${{ inputs.apim_env }}
        COMMIT_HASH: ${{ inputs.commit_hash }}
        TAG: ${{ inputs.tag }}
      run: |
        set -euo pipefail
        /bin/bash ./scripts/workflow/service-automation-apim-tests.sh
