name: "Service automation tests action"
description: "Run service automation tests"

inputs:
  environment:
    description: "The name of the environment to action the infrastructure"
    required: true
  workspace:
    description: "The name of the workspace to action the infrastructure into."
    required: true
  aws_region:
    description: "AWS region"
    required: true
  test_tag:
    description: "The name of the feature tag that identifies the tests to run"
    required: true
  test_type:
    description: "The name of the type of test report that will be generated (e.g., bdd, apim, ui)"
    required: true
  api_name:
    description: "The name of the API to test (for APIM tests, e.g., dos-search)"
    required: false
  apim_env:
    description: "The APIM environment to test (for APIM tests, e.g., internal-dev, internal-qa)"
    required: false
  commit_hash:
    description: "The commit hash, set by the CI/CD pipeline workflow"
    required: false
  ref:
    description: "The branch, tag or SHA to build and deploy from"
    required: false

runs:
  using: "composite"
  steps:
    - name: Run service automation tests script
      id: run-service-automation-tests-script
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws_region }}
        WORKSPACE: ${{ inputs.workspace }}
        ENVIRONMENT: ${{ inputs.environment }}
        TEST_TAG: ${{ inputs.test_tag }}
        TEST_TYPE: ${{ inputs.test_type }}
        COMMIT_HASH: ${{ inputs.commit_hash }}
        REF: ${{ inputs.ref }}
        API_NAME: ${{ inputs.api_name }}
        APIM_ENV: ${{ inputs.apim_env }}
      run: |
        set -euo pipefail
        /bin/bash ./scripts/workflow/service-automation-tests.sh
