name: "Service automation tests action"
description: "Run service automation tests"

inputs:
  environment:
    description: "The name of the environment to action the infrastructure"
    required: true
  workspace:
    description: "The name of the workspace to action the infrastructure into."
    required: true
  aws_region:
    description: "AWS region"
    required: true
  test_tag:
    description: "feature tag that identifies tests to be run"
    required: true
  test_type:
    description: "tag that identifies types of test and reports to be run"
    required: true
  commit_hash:
    description: "The commit hash, set by the CI/CD pipeline workflow"
    required: false
  ref:
    description: "The branch, tag or SHA to build and deploy from"
    required: false
  api_name:
    description: "API name for APIM proxy generation, required if test_type is apim"
    required: false
  apim_env:
    description: "APIM environment for proxy generation, required if test_type is apim"
    required: false


runs:
  using: "composite"
  steps:
    - name: Run service automation tests script
      id: run-service-automation-tests-script
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws_region }}
        WORKSPACE: ${{ inputs.workspace }}
        ENVIRONMENT: ${{ inputs.environment }}
        TEST_TAG: ${{ inputs.test_tag }}
        TEST_TYPE: ${{ inputs.test_type }}
        COMMIT_HASH: ${{ inputs.commit_hash }}
        REF: ${{ inputs.ref }}
        API_NAME: ${{ inputs.api_name }}
        APIM_ENV: ${{ inputs.apim_env }}
      run: |
        set -euo pipefail
        /bin/bash ./scripts/workflow/service-automation-tests.sh
