name: "Install npm dependencies action"
description: "Installs npm dependencies"

inputs:
  code_directory:
    description: 'Directory that holds package json '
    required: true
runs:
  using: "composite"
  steps:
    - name: Install node dependencies
      id: install_node_dependencies
      shell: bash
      run: |
        export FRONT_END_DIR=${{ inputs.code_directory }}
        /bin/bash ./scripts/workflow/install-npm-dependencies.sh
