version: 2

updates:

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/services/etl-ods"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/services/data-migration"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/services/gp-search"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/services/crud-apis"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/services/dos-ingestion-api"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/services/read-only-viewer"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/sandbox/dos-ingest-sandbox"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/application/packages/ftrs_aws_local"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/application/packages/python"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/tests/service_automation"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/sandbox/dos-ingest-sandbox"
    schedule:
      interval: "daily"
