name: "Push tag action"
description: "Pushes tag to repository."

inputs:
  tag_to_push:
    description: "The tag to push"
    required: true
  tag_overwrite:
    description: "Yes No flag to configure overwriting (or moving) the tag if it exists already"
    required: false
    default: "no"
runs:
  using: "composite"
  steps:
    - name: Push tag
      shell: bash
      env:
        TAG_TO_PUSH: ${{ inputs.tag_to_push }}
        TAG_OVERWRITE: ${{ inputs.tag_overwrite }}
      run: |
        . uec-dos-management/scripts/workflow/push-tag.sh
