name: 'Proxygen Docker Token Auth'
description: 'Request Docker registry credentials from Proxygen using an APIM access token'

inputs:
  api_name:
    description: 'Name of the API to access via Proxygen'
    required: true
  access_token:
    description: 'Access token for Proxygen API'
    required: true

outputs:
  docker_token:
    description: 'JSON response from Proxygen containing Docker registry credentials'
    value: ${{ steps.authenticate.outputs.docker_token }}

runs:
  using: 'composite'
  steps:
    - name: Fetch Docker token
      id: authenticate
      shell: bash
      env:
        API_NAME: ${{ inputs.api_name }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
      run: |
        set -euo pipefail

        if [ -z "${ACCESS_TOKEN:-}" ]; then
          echo "ACCESS_TOKEN input is required" >&2
          exit 1
        fi

        if [ -z "${API_NAME:-}" ]; then
          echo "API_NAME input is required" >&2
          exit 1
        fi

        if [ -z "${PROXYGEN_BASE_URL:-}" ]; then
          echo "PROXYGEN_BASE_URL environment variable is required" >&2
          exit 1
        fi

        # Mask secrets as early as possible
        echo "::add-mask::$ACCESS_TOKEN"

        BASE_URL="${PROXYGEN_BASE_URL%/}"
        TOKEN_ENDPOINT="${BASE_URL}/apis/${API_NAME}/docker-token"

        TMP_RESPONSE=$(mktemp)
        HTTP_STATUS=$(curl -sS -o "$TMP_RESPONSE" -w '%{http_code}' \
          --request GET --url "$TOKEN_ENDPOINT" --header "Authorization: Bearer ${ACCESS_TOKEN}") || {
          rm -f "$TMP_RESPONSE"
          echo "Failed to reach Proxygen API" >&2
          exit 1
        }

        RESPONSE_SIZE=$(wc -c < "$TMP_RESPONSE" | tr -d ' ')
        echo "Proxygen docker-token status=${HTTP_STATUS} size=${RESPONSE_SIZE}"

        DOCKER_TOKEN=$(cat "$TMP_RESPONSE")
        rm -f "$TMP_RESPONSE"

        echo "::add-mask::$DOCKER_TOKEN"

        printf 'docker_token=%s\n' "$DOCKER_TOKEN" >> "$GITHUB_OUTPUT"
        echo "✓ Docker token retrieved successfully"
