name: "Build service action"
description: "Builds a service."

inputs:
    service:
        description: "The name of the service to build"
        required: true
    directory:
        description: "The name of the directory to build in"
        required: true

runs:
  using: "composite"

  steps:
      - name: Build Service
        shell: bash
        env:
          SERVICE: ${{ inputs.service }}
          DIRECTORY: ${{ inputs.directory }}
        run: |
          /bin/bash ./uec-dos-management/scripts/workflow/build-service.sh
