name: "Run Performance Test action"
description: "Runs a performance test given an endpoint type and test type on the EC2 instance"

inputs:
  ec2-instance-id:
    description: "The EC2 instance ID to connect to"
    required: true
  endpoint:
    description: "The endpoint to run the performance test against"
    required: false
    default: ""
  environment:
    description: 'Environment to authenticate against (e.g., dev, test, prod)'
    required: true
  apim-env:
    description: "The environment for the APIM gateway"
    required: false
    default: ""
  workspace:
    description: "The workspace for the performance test"
    required: false
    default: ""
  aws-region:
    description: 'AWS region for Secrets Manager'
    required: false
    default: "eu-west-2"
  num-threads:
    description: "Number of threads for the performance test"
    required: true
  ramp-time:
    description: "Ramp up time for the performance test"
    required: true
  startup-delay:
    description: "Startup delay for the performance test"
    required: true
  duration:
    description: "Duration of the performance test"
    required: true
  throughput:
    description: "Throughput for the performance test"
    required: true
  throughput-period:
    description: "Throughput period for the performance test"
    required: true
  performance-results-bucket:
    description: "The S3 bucket to store performance test results"
    required: true
  stop-instance:
    description: "Whether to stop the EC2 instance after the test"
    required: true

runs:
  using: "composite"
  steps:

    - name: Run Test on Gateway
      shell: bash
      id: run
      run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ inputs.ec2-instance-id }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["cd /home/ssm-user",
                        "make run-performance-test-gateway AWS_REGION=${{ inputs.aws-region }} PLAN_NAME=IS_Test_Plan ENDPOINT=${{ inputs.endpoint }} PFX_PATH=./parameter_files/jmeter_pfx.pfx SECRET_NAME=/ftrs-directory-of-services/${{ inputs.environment }}/api-jmeter-pks-key NUM_THREADS=${{ inputs.num-threads }} RAMP_TIME=${{ inputs.ramp-time }} STARTUP_DELAY=${{ inputs.startup-delay }} DURATION=${{ inputs.duration }} THROUGHPUT=${{ inputs.throughput }} THROUGHPUT_PERIOD=${{ inputs.throughput-period }} PERFORMANCE_RESULTS_BUCKET=${{ inputs.performance-results-bucket }} JMETER_INSTANCE_ID=${{ inputs.ec2-instance-id }} STOP_INSTANCE=${{ inputs.stop-instance }}"]' \
            --query "Command.CommandId" \
            --output text)

          echo "command_id=$COMMAND_ID"
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
