name: "Run Performance Test action"
description: "Runs a performance test given a test file on a given EC2 instance"

inputs:
  ec2-instance-id:
    description: "The EC2 instance ID to connect to"
    required: true
  test-file:
    description: "The test file to run"
    required: true

runs:
  using: "composite"
  steps:

    - name: Run test file on EC2 instance
      shell: bash
      id: run
      run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-0921fa8d098e8b441" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["cd /home/ssm-user",
                         "pwd",
                         "make download-performance-files",
                         "make performance-test-mtls-jp AWS_REGION=eu-west-2 PLAN_NAME=IS_Test_Plan ENDPOINT=dos-search-ftrs-893.dev.ftrs.cloud.nhs.uk PFX_PATH=./parameter_files/jmeter_pfx.pfx SECRET_ID=/ftrs-directory-of-services/dev/api-jmeter-pks-key NUM_THREADS=10 RAMP_TIME=1 STARTUP_DELAY=10 DURATION=20 THROUGHPUT=10 THROUGHPUT_PERIOD=60"]' \
            --query "Command.CommandId" \
            --output text)

          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT


