name: "Run Performance Test action"
description: "Runs a performance test given a test file on a given EC2 instance"

inputs:
  ec2-instance-id:
    description: "The EC2 instance ID to connect to"
    required: true
  test-file:
    description: "The test file to run"
    required: true

runs:
  using: "composite"
  steps:

    - name: Run test file on EC2 instance
      shell: bash
      id: run
      run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ steps.lookup.outputs.instance_id }}" \
            --document-name "AWS-RunShellScript" \
            --parameters commands=["echo 'Running performance test'"] \
            --query "Command.CommandId" \
            --output text)

          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
