name: "Run SonarCloud static analysis"
description: "Perform SonarCloud static analysis"

inputs:
  sonar_organisation_key:
    description: "Sonar organisation key, used to identify the project"
    required: false
  sonar_project_key:
    description: "Sonar project key, used to identify the project"
    required: false
  sonar_token:
    description: "Sonar token, the API key"
    required: false
  python_version:
    description: "Python version for SonarCloud analysis"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Download code coverage reports"
      uses: actions/download-artifact@v6
      with:
        path: coverage-artifacts/
        pattern: coverage-*
        merge-multiple: true

    - name: "Find coverage files"
      id: coverage-files
      shell: bash
      run: |
        FILES=$(./scripts/workflow/prepare-coverage-files.sh)
        echo "files=$FILES" >> $GITHUB_OUTPUT

    - name: "Perform SonarCloud static analysis"
      uses: sonarsource/sonarqube-scan-action@v5.3.1
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        args: >
          -Dsonar.organization=${{ inputs.sonar_organisation_key }}
          -Dsonar.projectKey=${{ inputs.sonar_project_key }}
          -Dsonar.branch.name=${{ github.ref_name }}
          -Dsonar.python.version=${{ inputs.python_version }}
          -Dsonar.python.coverage.reportPaths=${{ steps.coverage-files.outputs.files }}
          -Dproject.settings=./scripts/config/sonar-scanner.properties
      continue-on-error: true
