name: "Check Python syntax and formatting"
description: "Checks correct syntax and Ruff formatting of Python code"

runs:
  using: "composite"
  steps:
    - name: Install Ruff
      shell: bash
      run: pip install ruff

    - name: Check Python syntax and formatting
      id: syntax_python
      shell: bash
      run: |
        ruff check .
        ruff format --check .
        export PRECOMMIT=false
        ./scripts/githooks/python-flake-pre-commit.sh
