name: "Deploy service action"
description: "Deploys a service into a Lambda."

inputs:
  service:
    description: "The name of the service to deploy"
    required: true
  directory:
    description: "The name of the directory to build in"
    required: true
  workspace:
    description: "The name of the workspace to deploy the service into."
    required: true
  artefact_sub_dir:
    description: "If deploying a custom artefact, specify its S3 subdirectory here."
    required: false
  artefact_bucket_name:
    description: "Name of bucket holding the artefacts for the domain"
    required: true
  environment:
    description: "The environment being updated"
    required: true
  ref:
    description: "The branch, tag or SHA to checkout"
    required: false

runs:
  using: "composite"

  steps:
    - name: Deploy Service
      shell: bash
      env:
        SERVICE: ${{ inputs.service }}
        APPLICATION_ROOT_DIR: ${{ inputs.directory }}
        TAG: ${{ inputs.ref }}
        WORKSPACE: ${{ inputs.workspace }}
        ARTEFACT_SUB_DIR: ${{ inputs.artefact_sub_dir }}
        ARTEFACT_BUCKET_NAME: ${{ inputs.artefact_bucket_name }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        /bin/bash ./uec-dos-management/scripts/workflow/deploy-service.sh
