vulnerabilities:
  - id: CVE-2025-50181
    # paths:
    #   - "gp-search/poetry.lock"
    #   - "tests/service_automation/poetry.lock"
    statement: "TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-576"
    expired_at: "2025-12-31"
  - id: CVE-2025-50182
    # paths:
    #   - "gp-search/poetry.lock"
    #   - "../tests/service_automation/poetry.lock"
    statement: "TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-576"
    expired_at: "2025-12-31"
  - id: CVE-2025-54121
    # paths:
    #   - "crud-apis/poetry.lock"
    statement: "TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-576"
    expired_at: "2025-12-31"
  - id: CVE-2025-46565
    # paths:
    #   - "read-only-viewer/package-lock.json"
    statement: "TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-412"
    expired_at: "2025-12-31"
  - id: CVE-2025-32395
    # paths:
    #   - "read-only-viewer/package-lock.json"
    statement: "TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-412"
    expired_at: "2025-12-31"
  - id: GHSA-67mh-4wv8-2f99
    # paths:
    #   - "read-only-viewer/package-lock.json"
    statement: "TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-412"
    expired_at: "2025-12-31"
