name: "EC2 Performance Clear Run Lock action"
description: "Clear the performance run lock file on an EC2 instance"

inputs:
  ec2-instance-id:
    description: "The instance ID of the EC2 instance to clear the performance run lock file from"
    required: true

runs:
  using: "composite"
  steps:

    - name: Clear Performance Run Lock
      id: clear-lock-file
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
      run: |
        COMMANDS=$(cat <<EOF
        [
          "cd /home/ssm-user",
          "sudo rm -f performance_run.lock"
        ]
        EOF
        )

        COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$EC2_INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Clear performance run lock file on EC2 instance $EC2_INSTANCE_ID" \
            --parameters "{\"commands\": $COMMANDS}" \
            --query "Command.CommandId" \
            --output text)

        echo "command_id (Clear Lock File)=$COMMAND_ID"
        echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

    - name: Wait for Clear Lock Command to Complete
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
        COMMAND_ID: ${{ steps.clear-lock-file.outputs.command_id }}
      run: |
          echo "Waiting for clear lock file command to complete..."
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID"
