name: "Start EC2 action"
description: "Start an EC2 instance"

inputs:
  ec2-name-tag:
    description: "The Name tag of the EC2 instance to start"
    required: true

outputs:
  ec2-instance-id:
    description: 'Instance ID of the started EC2 instance'
    value: ${{ steps.lookup.outputs.ec2_instance_id }}

runs:
  using: "composite"
  steps:
    - name: Look up EC2 instance ID by tag
      id: lookup
      shell: bash
      env:
        EC2_NAME_TAG: ${{ inputs.ec2-name-tag }}
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=$EC2_NAME_TAG" \
          --query "Reservations[0].Instances[0].InstanceId" \
          --output text)

        echo "ec2_instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT

    - name: Start EC2 instance
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ steps.lookup.outputs.ec2_instance_id }}
      run: |
        aws ec2 start-instances --instance-ids $EC2_INSTANCE_ID

    - name: Wait for instance to be running
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ steps.lookup.outputs.ec2_instance_id }}
      run: |
        aws ec2 wait instance-running --instance-ids $EC2_INSTANCE_ID

    - name: Show instance state
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ steps.lookup.outputs.ec2_instance_id }}
      run: |
        aws ec2 describe-instances \
          --instance-ids $EC2_INSTANCE_ID \
          --query "Reservations[0].Instances[0].State.Name"
