name: "Start EC2 action"
description: "Start an EC2 instance"

inputs:
  ec2-instance-id:
    description: "The instance ID of the EC2 instance to start"
    required: true

runs:
  using: "composite"
  steps:

    - name: Start EC2 instance
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
      run: |
        aws ec2 start-instances --instance-ids $EC2_INSTANCE_ID

    - name: Wait for instance to be running
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
      run: |
        aws ec2 wait instance-running --instance-ids $EC2_INSTANCE_ID

    - name: Show instance state
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
      run: |
        aws ec2 describe-instances \
          --instance-ids $EC2_INSTANCE_ID \
          --query "Reservations[0].Instances[0].State.Name"
