name: 'Deploy API Proxy to APIM environment'
description: 'Deploy an API Proxy into an APIM environment'

inputs:
  api_name:
    description: 'Name of the API to deploy'
    required: true
  workspace:
    description: 'Workspace identifier (e.g., FTRS-000)'
    required: true
  environment:
    description: 'FTRS environment to deploy to (e.g., dev, test, prod)'
    required: true
  apim_env:
    description: 'APIM environment to deploy the API Proxy into (e.g., internal-dev)'
    required: true
  access_token:
    description: 'Access Token for the Proxygen API'
    required: true
  proxygen_url:
    description: 'Proxygen API URL'
    required: true
  version_tag:
    description: 'Version applied to the deployed proxy'
    required: false

outputs:
  deployment_status:
    description: 'Status of the deployment'
    value: ${{ steps.deploy.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Validate workspace format
      if: ${{ !contains(inputs.apim_env, 'sandbox') }}
      shell: bash
      run: |
        if [[ ! "${{ inputs.workspace }}" =~ ^ftrs-[0-9]+$ ]]; then
          echo "Error: Workspace must be in format ftrs-#### (e.g., ftrs-1234, ftrs-001, ftrs-99999)"
          exit 1
        fi
        echo "Workspace format validated: ${{ inputs.workspace }}"

    - name: Modify OAS Specification
      if: ${{ !contains(inputs.apim_env, 'sandbox') }}
      id: modify-spec
      shell: bash
      run: |
        export API_NAME="${{ inputs.api_name }}"
        export WORKSPACE="${{ inputs.workspace }}"
        export PROXY_ENV="${{ inputs.apim_env }}"

        chmod +x ./scripts/workflow/modify-oas-spec.sh
        MODIFIED_SPEC_PATH=$(./scripts/workflow/modify-oas-spec.sh)

        if [ $? -eq 0 ]; then
          echo "modified_spec_path=$MODIFIED_SPEC_PATH" >> $GITHUB_OUTPUT
          echo "OAS spec modified successfully"
        else
          echo "Failed to modify OAS spec"
          exit 1
        fi

    - name: Modify Sandbox OAS Specification
      if: ${{ contains(inputs.apim_env, 'sandbox') }}
      id: modify-sandbox-spec
      shell: bash
      run: |
        export API_NAME="${{ inputs.api_name }}"
        export PROXY_ENV="${{ inputs.apim_env }}"
        export VERSION_TAG="${{ inputs.version_tag }}"

        chmod +x ./scripts/workflow/modify-oas-sandbox-spec.sh
        read -r MODIFIED_SPEC_PATH TARGET_SPEC_FILE < <(./scripts/workflow/modify-oas-sandbox-spec.sh)

        if [ $? -eq 0 ]; then
          echo "modified_spec_path=$MODIFIED_SPEC_PATH" >> $GITHUB_OUTPUT
          echo "target_spec_file_abs=$TARGET_SPEC_FILE" >> $GITHUB_OUTPUT
          echo "OAS spec modified successfully"
        else
          echo "Failed to modify OAS spec"
          exit 1
        fi

    - name: Deploy API Proxy to APIM environment
      id: deploy
      shell: bash
      run: |
        export API_NAME="${{ inputs.api_name }}"
        export WORKSPACE="${{ inputs.workspace }}"
        export PROXY_ENV="${{ inputs.apim_env }}"
        export ACCESS_TOKEN="${{ inputs.access_token }}"
        export PROXYGEN_URL="${{ inputs.proxygen_url }}"
        export VERSION_TAG="${{ inputs.version_tag }}"
        export IS_SANDBOX="${{ contains(inputs.apim_env, 'sandbox') }}"

        if [[ "$IS_SANDBOX" == 'true' ]]; then
          export MODIFIED_SPEC_PATH="${{ steps.modify-sandbox-spec.outputs.modified_spec_path }}"
          export TARGET_SPEC_FILE="${{ steps.modify-sandbox-spec.outputs.target_spec_file_abs }}"
        else
          export MODIFIED_SPEC_PATH="${{ steps.modify-spec.outputs.modified_spec_path }}"
        fi

        chmod +x ./scripts/workflow/deploy-to-apim.sh
        ./scripts/workflow/deploy-to-apim.sh

        if [ $? -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "${{ inputs.api_name }} deployed successfully to APIM ${{ inputs.apim_env }} environment"
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "${{ inputs.api_name }} deployment to ${{ inputs.apim_env }} failed"
          exit 1
        fi

    - name: Output deployment details
      shell: bash
      run: |
        VERSION_TAG="${{ inputs.version_tag }}"
        echo "Deployment Summary:"
        echo "- API Name: ${{ inputs.api_name }}"
        echo "- Workspace: ${{ inputs.workspace }}"
        echo "- Environment: ${{ inputs.environment }}"
        echo "- APIM Environment: ${{inputs.apim_env }}"
        if [ -n "$VERSION_TAG" ]; then
          echo "- Version Tag: $VERSION_TAG"
        fi
        echo "- Status: ${{ steps.deploy.outputs.status }}"
