name: 'Cleardown API Proxy from APIM environment'
description: 'Remove an API Proxy from an APIM environment'

inputs:
  api_name:
    description: 'Name of the API to cleardown'
    required: true
  workspace:
    description: 'Workspace identifier (e.g., ftrs-000). If specified, a workspaced proxy will be cleared from the APIM environment'
    required: false
  environment:
    description: 'The environment (e.g., dev, test, prod)'
    required: true
  apim_env:
    description: 'APIM environment to cleardown the API Proxy from (e.g., internal-dev, internal-qa, int, ref, prod)'
    required: true
  aws_region:
    description: 'AWS region for Secrets Manager'
    required: true
  proxygen_url:
    description: 'Proxygen API URL'
    required: true

outputs:
  cleardown_status:
    description: 'Status of the cleardown'
    value: ${{ steps.cleardown.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Get Proxygen Access Token
      id: get-token
      uses: ./.github/actions/authenticate-apim
      with:
        api_name: ${{ inputs.api_name }}
        environment: ${{ inputs.environment }}
        aws_region: ${{ inputs.aws_region }}

    - name: Cleardown API Proxy from APIM environment
      id: cleardown
      shell: bash
      env:
        API_NAME: ${{ inputs.api_name }}
        WORKSPACE: ${{ inputs.workspace }}
        PROXY_ENV: ${{ inputs.apim_env }}
        ACCESS_TOKEN: ${{ steps.get-token.outputs.access_token }}
        PROXYGEN_URL: ${{ inputs.proxygen_url }}
      run: |
        set -euo pipefail

        STATUS=$(./scripts/workflow/cleardown-apim-proxy.sh | tail -n1)
        if [ -z "${STATUS:-}" ]; then
          echo "Cleardown script returned no status" >&2
          exit 1
        fi

        printf 'status=%s\n' "$STATUS" >> "$GITHUB_OUTPUT"

    - name: Output cleardown details
      shell: bash
      env:
        API_NAME: ${{ inputs.api_name }}
        WORKSPACE: ${{ inputs.workspace }}
        ENVIRONMENT: ${{ inputs.environment }}
        APIM_ENV: ${{ inputs.apim_env }}
        STATUS: ${{ steps.cleardown.outputs.status }}
      run: |
        set -euo pipefail
        echo "Cleardown Summary:"
        echo "- API Name: $API_NAME"
        echo "- Workspace: $WORKSPACE"
        echo "- Environment: $ENVIRONMENT"
        echo "- APIM Environment: $APIM_ENV"
        echo "- Status: $STATUS"
