name: "Stop EC2 action"
description: "Stop an EC2 instance"

inputs:
  ec2-instance-id:
    description: "The instance ID of the EC2 instance to stop"
    required: true

runs:
  using: "composite"
  steps:

    - name: Clear Performance Run Lock
      id: clear-lock-file
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
      run: |
        COMMANDS=$(cat <<EOF
        [
          "cd /home/ssm-user",
          "sudo rm -f performance_test_run.lock"
        ]
        EOF
        )

        COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$EC2_INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters "{\"commands\": $COMMANDS}" \
            --query "Command.CommandId" \
            --output text)

        echo "command_id (Clear Lock File)=$COMMAND_ID"
        echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

    - name: Wait for Clear Lock Command to Complete
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
        COMMAND_ID: ${{ steps.clear-lock-file.outputs.command_id }}
      run: |
          echo "Waiting for performance config download to complete..."
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID"

    - name: Stop EC2 instance
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
      run: |
        aws ec2 stop-instances --instance-ids $EC2_INSTANCE_ID

    - name: Wait for instance to be stopped
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
      run: |
        aws ec2 wait instance-stopped --instance-ids $EC2_INSTANCE_ID

    - name: Show instance state
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
      run: |
        aws ec2 describe-instances \
          --instance-ids $EC2_INSTANCE_ID \
          --query "Reservations[0].Instances[0].State.Name"
