#!/usr/bin/env python3
"""
Generate Terraform tfvars files from the Toggle Registry.

This script reads the toggle-registry.yaml and generates stacks.auto.tfvars files
for each environment based on stack toggle configurations.
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Dict, Any

try:
    import yaml
except ImportError:
    print("Error: PyYAML is required. Install it with: pip install pyyaml")
    sys.exit(1)


def load_toggle_registry(registry_path: Path) -> Dict[str, Any]:
    """Load the toggle registry YAML file."""
    with open(registry_path, 'r') as f:
        return yaml.safe_load(f)


def generate_stack_tfvars(toggle_registry: Dict[str, Any], environment: str) -> str:
    """Generate tfvars content for a specific environment."""
    stack_toggles = toggle_registry.get('stack_toggles', [])
    
    if not stack_toggles:
        return "# No stack toggles defined\n"
    
    tfvars_lines = [
        "# Auto-generated from toggle-registry.yaml",
        "# DO NOT EDIT THIS FILE MANUALLY",
        f"# Environment: {environment}",
        ""
    ]
    
    for toggle in stack_toggles:
        toggle_id = toggle.get('id', '')
        terraform_var = toggle.get('terraform_variable', '')
        env_values = toggle.get('environments', {})
        
        if terraform_var and environment in env_values:
            value = 'true' if env_values[environment] else 'false'
            tfvars_lines.append(f"{terraform_var} = {value}")
    
    return '\n'.join(tfvars_lines) + '\n'


def write_tfvars_file(environment_dir: Path, content: str) -> None:
    """Write the tfvars content to stacks.auto.tfvars in the environment directory."""
    tfvars_file = environment_dir / 'stacks.auto.tfvars'
    
    with open(tfvars_file, 'w') as f:
        f.write(content)
    
    print(f"Generated: {tfvars_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate stacks.auto.tfvars files from toggle-registry.yaml'
    )
    parser.add_argument(
        '--registry',
        type=Path,
        default=Path(__file__).parent.parent / 'infrastructure' / 'toggles' / 'toggle-registry.yaml',
        help='Path to toggle-registry.yaml'
    )
    parser.add_argument(
        '--environments-dir',
        type=Path,
        default=Path(__file__).parent.parent / 'infrastructure' / 'environments',
        help='Path to environments directory'
    )
    parser.add_argument(
        '--environment',
        type=str,
        help='Generate for specific environment only (e.g., dev, test, prod)'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Print generated content without writing files'
    )
    
    args = parser.parse_args()
    
    # Validate registry file exists
    if not args.registry.exists():
        print(f"Error: Toggle registry not found at {args.registry}")
        sys.exit(1)
    
    # Load toggle registry
    try:
        toggle_registry = load_toggle_registry(args.registry)
    except Exception as e:
        print(f"Error loading toggle registry: {e}")
        sys.exit(1)
    
    # Get list of environments
    stack_toggles = toggle_registry.get('stack_toggles', [])
    if not stack_toggles:
        print("Warning: No stack toggles found in registry")
        return
    
    # Extract all unique environments from the toggle registry
    all_environments = set()
    for toggle in stack_toggles:
        env_values = toggle.get('environments', {})
        all_environments.update(env_values.keys())
    
    # Filter to specific environment if requested
    if args.environment:
        if args.environment not in all_environments:
            print(f"Error: Environment '{args.environment}' not found in toggle registry")
            print(f"Available environments: {', '.join(sorted(all_environments))}")
            sys.exit(1)
        environments_to_process = [args.environment]
    else:
        environments_to_process = sorted(all_environments)
    
    # Generate tfvars for each environment
    for env in environments_to_process:
        env_dir = args.environments_dir / env
        
        # Check if environment directory exists
        if not env_dir.exists():
            print(f"Warning: Environment directory not found: {env_dir}")
            continue
        
        # Generate tfvars content
        tfvars_content = generate_stack_tfvars(toggle_registry, env)
        
        if args.dry_run:
            print(f"\n--- {env}/stacks.auto.tfvars ---")
            print(tfvars_content)
        else:
            write_tfvars_file(env_dir, tfvars_content)
    
    if not args.dry_run:
        print(f"\nSuccessfully generated tfvars files for {len(environments_to_process)} environment(s)")


if __name__ == '__main__':
    main()
