project          = "ftrs-directory-of-services"
project_owner    = "nhs-uec"
service          = "uec-ftrs"
cost_centre      = "P0675"
data_type        = "PCD"
project_type     = "Pilot"
public_facing    = "no"
service_category = "bronze"

artefacts_bucket_name = "artefacts-bucket"
