name: "Run Performance Test Proxy action"
description: "Runs a performance test on the Proxy given a test type on a given EC2 instance"

inputs:
  ec2-instance-id:
    description: "The EC2 instance ID to connect to"
    required: true
  endpoint:
    description: "The endpoint to run the performance test against"
    required: true
  environment:
    description: 'Environment to authenticate against (e.g., dev, test, prod)'
    required: true
  aws-region:
    description: 'AWS region for Secrets Manager'
    required: true
  apim-env:
    description: "The environment for the APIM proxy"
    required: true
  api-key:
    description: "The API key for the APIM proxy"
    required: true
  kid:
    description: "The name of the key for the JWT token"
    required: true
  performance-results-bucket:
    description: "The S3 bucket to store performance test results"
    required: true
  stop-instance:
    description: "Whether to stop the EC2 instance after the test"
    required: true

runs:
  using: "composite"
  steps:

    - name: Run Test on Gateway
      shell: bash
      id: run
      run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ inputs.ec2-instance-id }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["cd /home/ssm-user",
                        "make run-performance-test-gateway AWS_REGION=${{ inputs.aws-region }} PLAN_NAME=IS_Test_Plan ENDPOINT=${{ inputs.endpoint }} PFX_PATH=./parameter_files/jmeter_pfx.pfx SECRET_ID=/ftrs-directory-of-services/${{ inputs.environment }}/api-jmeter-pks-key NUM_THREADS=${{ inputs.num-threads }} RAMP_TIME=${{ inputs.ramp-time }} STARTUP_DELAY=${{ inputs.startup-delay }} DURATION=${{ inputs.duration }} THROUGHPUT=${{ inputs.throughput }} THROUGHPUT_PERIOD=${{ inputs.throughput-period }} PERFORMANCE_RESULTS_BUCKET=${{ inputs.performance-results-bucket }} JMETER_INSTANCE_ID=${{ inputs.ec2-instance-id }} STOP_INSTANCE=${{ inputs.stop-instance }}"]' \
            --query "Command.CommandId" \
            --output text)

          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
