[project]
name = "ftrs-python-packages"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.12,<4.0.0"
dependencies = [
    "pydantic (>=2.11.1,<3.0.0)",
    "boto3-stubs[dynamodb] (>=1.37.33,<2.0.0)",
]

[tool.poetry]
packages = [
  { include = "ftrs_data_layer", from = "." },
]


[tool.poetry.group.dev.dependencies]
boto3 = "^1.37.24"
aws-lambda-powertools = "^3.9.0"
pytest = "^8.3.5"
pytest-cov = "^6.1.0"
moto = {extras = ["dynamodb"], version = "^5.1.2"}
ruff = "^0.11.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v --cov=. --cov-report=term-missing --cov-fail-under=80 --cov-branch --cov-context=test"
testpaths = ["**/ftrs_data_layer/tests/"]

[tool.coverage.run]
omit = ["*/tests/*"]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "ANN", "LOG", "PL", "TRY", "FURB"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
