# Tables to migrate data from source database
LEGACY_DOS_TABLES = [
    "servicestatuses",
    "servicetypes",
    "services",
    "agegroups",
    "dispositions",
    "dispositionservicetypes",
    "dispositiongroups",
    "dispositiongroupdispositions",
    "dispositiongroupservicetypes",
    "genders",
    "locations",
    "openingtimedays",
    "organisationtypes",
    "referralroles",
    "symptomdiscriminators",
    "symptomdiscriminatorsynonyms",
    "symptomgroups",
    "symptomgroupsymptomdiscriminators",
]
