name: 'Build index'
description: 'Build index'

inputs:
  workspace:
    description: "The name of the workspace"
  environment:
    description: 'Environment to authenticate against (e.g., dev, test, prod)'
    required: true
  domain:
    description: "The name of the domain to deploy from. If not supplied, we will deploy from the domain that has invoked the workflow"
    required: false
    default: "ftrs-dos-dev-osc"
  index:
    description: "The OpenSearch index name to create"
    required: false
    default: "organisation"
  aws_region:
    description: "AWS region to use for AWS CLI calls (optional). If empty, the script will rely on AWS CLI defaults or detect it."
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Build Service
      id: build_index
      shell: bash
      env:
        # map inputs to step-level env so the script can read them
        INDEX: ${{ inputs.index }}
        OPEN_SEARCH_DOMAIN: ${{ inputs.domain }}
        WORKSPACE: ${{ inputs.workspace }}
        ENVIRONMENT: ${{ inputs.environment }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        AWS_REGION: ${{ inputs.aws_region }}
        AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
      run: |
        set -euo pipefail

        echo "Using OPEN_SEARCH_DOMAIN=${OPEN_SEARCH_DOMAIN} and INDEX=${INDEX} (workspace=${WORKSPACE})"

        # Call the Python signer to create the index (uses boto3/botocore SigV4 signing)
        # Ensure Python deps are available (requests, boto3)
        python3 -m pip install --upgrade pip >/dev/null 2>&1 || true
        python3 -m pip install requests boto3 >/dev/null 2>&1 || true

        python3 ./scripts/workflow/create_open_search_index.py
