name: 'Build index'
description: 'Build index'

inputs:
  workspace:
    description: "The name of the workspace"
  environment:
    description: 'Environment to authenticate against (e.g., dev, test, prod)'
    required: true
  domain:
    description: "The name of the domain to deploy from. If not supplied, we will deploy from the domain that has invoked the workflow"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Build Service
      id: build_index
      shell: bash
      run: |
        ./scripts/workflow/build-open-search-index.sh
