name: 'Build index'
description: 'Build index'

inputs:
  workspace:
    description: "The name of the workspace"
  environment:
    description: 'Environment to authenticate against (e.g., dev, test, prod)'
    required: true
  domain:
    description: "The name of the domain to deploy from. If not supplied, we will deploy from the domain that has invoked the workflow"
    required: false
    default: "ftrs-dos-dev-osc"
  index:
    description: "The OpenSearch index name to create"
    required: false
    default: "os-index"
  aws_region:
    description: "AWS region to use for AWS CLI calls (optional). If empty, the script will rely on AWS CLI defaults or detect it."
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Build Service
      id: build_index
      shell: bash
      env:
        # map inputs to step-level env so the script can read them
        INDEX: ${{ inputs.index }}
        OPEN_SEARCH_DOMAIN: ${{ inputs.domain }}
        WORKSPACE: ${{ inputs.workspace }}
        ENVIRONMENT: ${{ inputs.environment }}
        AWS_REGION: ${{ inputs.aws_region }}
        AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
      run: |
        set -euo pipefail

        echo "Using OPEN_SEARCH_DOMAIN=${OPEN_SEARCH_DOMAIN} and INDEX=${INDEX} (workspace=${WORKSPACE})"

        # Ensure the build script is executable in case the checkout removed the execute bit
        chmod +x ./scripts/workflow/build-open-search-index.sh || true

        ./scripts/workflow/build-open-search-index.sh
