# `*:latest` will be replaced with a corresponding version stored in the '.tool-versions' file
# hadolint ignore=DL3007
# checkov:skip=CKV_DOCKER_2: Temp suppression JIRA-445
# checkov:skip=CKV_DOCKER_3: Temp suppression JIRA-445
# checkov:skip=CKV_DOCKER_7: Temp suppression JIRA-445
FROM python:latest
