# `*:latest` will be replaced with a corresponding version stored in the '.tool-versions' file
# hadolint ignore=DL3007
# checkov:skip=CKV_DOCKER_2: TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-410
# checkov:skip=CKV_DOCKER_3: TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-410
# checkov:skip=CKV_DOCKER_7: TODO https://nhsd-jira.digital.nhs.uk/browse/FDOS-410
FROM python:latest
