name: "EC2 Performance Check Test Running action"
description: "Checks the EC2 to see if a performance test is currently running"

inputs:
  ec2-instance-id:
    description: "The EC2 instance ID to check for the performance test lock file"
    required: true
  lock-file-path:
    description: "The path to the lock file on the EC2 instance that indicates a performance test is running"
    required: false
    default: "/home/ssm-user/performance_run.lock"

outputs:
  performance-test-running:
    description: "Whether a performance test is currently running on the EC2 instance (true/false)"
    value: ${{ steps.retrieve-lock-file-result.outputs.performance_test_running }}

runs:
  using: "composite"
  steps:
    - name: Check for performance test lock file
      id: check-lock-file
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
        LOCK_FILE_PATH: ${{ inputs.lock-file-path }}
      run: |
        COMMANDS=$(cat <<EOF
        [
          "if [ -f '${LOCK_FILE_PATH}' ]; then echo true; else echo false; fi"
        ]
        EOF
        )

        COMMAND_ID=$(
          aws ssm send-command \
          --instance-ids "$EC2_INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Check performance test lock file of $LOCK_FILE_PATH" \
          --parameters "{\"commands\": $COMMANDS}" \
          --query "Command.CommandId" \
          --output text)

          echo "command_id (Check Performance Test Lock File)=$COMMAND_ID"
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

    - name: Wait for Check Lock File Command to Complete
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
        COMMAND_ID: ${{ steps.check-lock-file.outputs.command_id }}
      run: |
          echo "Waiting for check lock file command to complete..."
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID"

    - name: Retrieve Check Lock File Command Result
      id: retrieve-lock-file-result
      shell: bash
      env:
        EC2_INSTANCE_ID: ${{ inputs.ec2-instance-id }}
        COMMAND_ID: ${{ steps.check-lock-file.outputs.command_id }}
      run: |
          FILE_EXISTS=$(aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID" \
            --query "StandardOutputContent" \
            --output text)

          echo "Command output: $FILE_EXISTS"
          echo "performance_test_running=$FILE_EXISTS"
          echo "performance_test_running=$FILE_EXISTS" >> $GITHUB_OUTPUT
