name: Run SonarCloud analysis
on:
  workflow_call:
    inputs:
      environment:
        description: "The deployment environment"
        required: true
        type: string

jobs:
  download-coverage-report:
    name: "Download python coverage reports"
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: ./.github/actions/configure-credentials
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}
          multi_domain: false

      - name: "Download code coverage reports"
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: .*-coverage
          merge-multiple: true

      - name: "Run sonarcloud analysis"
        run:  echo "Run analysis - placeholder"

