name: Build service workflow

on:
  workflow_call:
    inputs:
      package_name:
        description: "The name of the package to build"
        required: true
        type: string
      python_version:
        description: 'The version of Python'
        required: true
        type: string
      commit_hash:
        description: "The commit hash, set by the CI/CD pipeline workflow"
        required: true
        type: string
      environment:
        description: "The deployment environment"
        required: true
        type: string
      repo_name:
        description: "The name of the Git repo"
        required: true
        type: string
      workspace:
          description: "The name of the workspace to deploy the infrastructure into"
          required: true
          type: string
      application_tag:
          description: "The application tag identifying the timeline in the repository to deploy from"
          required: false
          type: string

jobs:
  build-service:
    name: "Build package - ${{ inputs.package_name }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install asdf"
        uses: asdf-vm/actions/setup@v3.0.2
        with:
          asdf_branch: v0.15.0

      - name: "Cache asdf tools"
        id: asdf-cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf
          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}

      - name: "Install tools from .tool-versions"
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v3.0.2

      - name: "Install project"
        run: make install
        working-directory: application/packages/${{ inputs.package_name }}

      - name: "Run linting"
        run: make lint
        working-directory: application/packages/${{ inputs.package_name }}

      - name: "Run unit tests"
        run: make unit-test
        working-directory: application/packages/${{ inputs.package_name }}

      - name: "Build service"
        run:  make build
        working-directory: application/packages/${{ inputs.package_name }}
        env:
          SERVICE: ${{ inputs.service_name }}
          PYTHON_VERSION: ${{ inputs.python_version }}
          APPLICATION_TAG: ${{ inputs.application_tag }}
          ENVIRNOMENT: ${{ inputs.environment }}
          REPO_NAME: ${{ inputs.repo_name }}

      - name: "Configure AWS Credentials"
        uses: ./.github/actions/configure-credentials
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}
          multi_domain: false

      - name: "Publish artefacts to S3"
        run: make publish
        working-directory: application/packages/${{ inputs.package_name }}
        env:
          PACKAGE: ${{ inputs.package_name }}
          COMMIT_HASH: ${{ inputs.commit_hash }}
          ENVIRNOMENT: ${{ inputs.environment }}
          REPO_NAME: ${{ inputs.repo_name }}
          WORKSPACE: ${{ inputs.workspace }}
          APPLICATION_TAG: ${{ inputs.application_tag }}

      - name: "Publish artefacts to GitHub"
        uses: actions/upload-artifact@v4.6.1
        with:
          name: ${{ inputs.package_name }}-package-artefacts
          path: build/packages/${{ inputs.package_name }}/
          if-no-files-found: error
