name: Build service workflow

on:
  workflow_call:
    inputs:
      service_name:
        description: "The name of the service to build"
        required: true
        type: string
      python_version:
        description: 'The version of Python'
        required: true
        type: string
      commit_hash:
        description: "The commit hash, set by the CI/CD pipeline workflow"
        required: true
        type: string
      environment:
        description: "The deployment environment"
        required: true
        type: string
      repo_name:
        description: "The name of the Git repo"
        required: true
        type: string
      workspace:
          description: "The name of the workspace to deploy the infrastructure into"
          required: true
          type: string
      application_tag:
          description: "The application tag identifying the timeline in the repository to deploy from"
          required: false
          type: string

jobs:
  build-service:
    name: "Build service - ${{ inputs.service_name }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Build service"
        run: make build
        env:
          SERVICE: ${{ inputs.service_name }}
          PYTHON_VERSION: ${{ inputs.python_version }}
          APPLICATION_TAG: ${{ inputs.application_tag }}
          ENVIRONMENT: ${{ inputs.environment }}
          REPO_NAME: ${{ inputs.repo_name }}

      - name: "Configure AWS Credentials"
        uses: ./.github/actions/configure-credentials
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}
          multi_domain: false

      - name: "Publish artefacts to S3"
        run: cd services/${{ inputs.service_name }} && make publish
        env:
          SERVICE: ${{ inputs.service_name }}
          COMMIT_HASH: ${{ inputs.commit_hash }}
          ENVIRONMENT: ${{ inputs.environment }}
          REPO_NAME: ${{ inputs.repo_name }}
          WORKSPACE: ${{ inputs.workspace }}
          APPLICATION_TAG: ${{ inputs.application_tag }}

      - name: "Publish artefacts to GitHub"
        uses: actions/upload-artifact@v4.6.1
        with:
          name: ${{ inputs.service_name }}-artefacts
          path: build/services/${{ inputs.service_name }}/
          if-no-files-found: error
