name: Pipeline Deploy Account Level Infrastructure
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      tag:
        description: "Specify the tag to be used for deployment"
        required: false
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

jobs:
  metadata:
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml

  deploy-account-infrastructure-plan:
    name: "Plan account level infrastructure deployment"
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: ${{ needs.metadata.outputs.environment }}
      domain: ${{ needs.metadata.outputs.reponame }}
      workspace: ${{ needs.metadata.outputs.workspace }}
      tag: ${{ inputs.tag }}
      stacks: "['terraform_management','account_wide']"
      action: plan
    secrets: inherit

  manual-approval:
    name: "Manual approval for account level infrastructure deployment"
    needs:
      [
        metadata,
        deploy-account-infrastructure-plan,
      ]
    runs-on: ubuntu-latest
    environment: "${{ needs.metadata.outputs.environment }}-protected"
    steps:
      - name: Approval required
        run: echo "Deployment paused for manual approval. Please approve in the Actions tab."

  deploy-account-infrastructure-apply:
    name: "Deploy account level infrastructure"
    needs:
      [
        metadata,
        manual-approval,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: ${{ needs.metadata.outputs.environment }}
      domain: ${{ needs.metadata.outputs.reponame }}
      workspace: ${{ needs.metadata.outputs.workspace }}
      tag: ${{ inputs.tag }}
      stacks: "['terraform_management','account_wide']"
      action: apply
    secrets: inherit
