name: Pipeline Deployment Application Development Environment
# Intended to run if
# - dependabot PR is labelled Test Ready
# - changes pushed to task branch
# - changes pushed to main branch
on:
  push:
    branches:
      - main
      - 'task/*'
  pull_request:
    types: [ labeled ]

jobs:
  metadata:
    if: ( ${{ github.event.label.name == 'Test Ready' && startswith(github.head_ref, 'dependabot/') }} ) || ( ${{ github.event_name == 'push' }} && ( ${{ startswith(github.ref_name, 'task/') || startswith(github.ref_name, 'main') }} ) )
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml

  quality-checks:
    name: "Quality Check"
    needs:
      [
        metadata,
      ]
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/quality-checks.yaml
    with:
      environment: dev
      workspace: ${{ needs.metadata.outputs.workspace }}
      stacks: '["account_wide", "terraform_management"]'
    secrets: inherit

  deploy-dev-account-infrastructure-plan:
    name: "TF Plan dev account level infrastructure"
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: ${{ needs.metadata.outputs.environment }}
      domain: ${{ needs.metadata.outputs.reponame }}
      workspace: ${{ needs.metadata.outputs.workspace }}
      tag: ${{ inputs.tag }}
      stacks: "['gp_search']"
      action: plan
    secrets: inherit

  manual-approval:
    name: "Manual approval for account level infrastructure deployment"
    needs:
      [
        metadata,
        deploy-dev-account-infrastructure-plan,
      ]
    runs-on: ubuntu-latest
    environment: "${{ needs.metadata.outputs.environment }}-protected"
    steps:
      - name: Approval required
        run: echo "Deployment paused for manual approval. Please approve in the Actions tab."

  deploy-dev-account-infrastructure-apply:
    name: "TFApply for Dev account infrastructure"
    needs:
      [
        metadata,
        manual-approval,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: ${{ needs.metadata.outputs.environment }}
      domain: ${{ needs.metadata.outputs.reponame }}
      workspace: ${{ needs.metadata.outputs.workspace }}
      tag: ${{ inputs.tag }}
      stacks: "['gp_search']"
      action: apply
    secrets: inherit

  slack-notifications:
    name: "Send Notification to Slack"
    needs: [
      metadata,
      quality-checks,
    ]
    if: always()
    uses: ./.github/workflows/slack-notifications.yaml
    with:
      env: dev
    secrets: inherit
