name: Promote artefacts workflow
run-name: Promote ${{ inputs.type }} - ${{ inputs.name }} artefacts

permissions:
  id-token: write
  contents: read
on:
  workflow_call:
    inputs:
      workspace:
        description: "The name of the workspace to deploy the application into"
        required: true
        type: string # TEMP
      environment:
        description: "The deployment environment"
        required: true
        type: string
        default: "mgmt"
      repo_name:
        description: "The name of the Git repo"
        required: true
        type: string
      artefact_promotion_type:
        description: "The type of artefact promotion to perform"
        required: true
        type: string
      type:
        description: "The type of permissions (e.g., account, app)"
        required: true
        type: string
      release_tag:
        description: "The release tag for the artefact"
        required: false
        type: string
      prerelease_tag:
        description: "The prerelease tag for the artefact"
        required: false
        type: string

jobs:
  promote-artefacts:
    name: "Promote ${{ inputs.type }} - ${{ inputs.name }} artefacts"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Configure AWS Credentials"
        uses: ./.github/actions/configure-credentials
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}
          type: ${{ inputs.type }}
          environment: ${{ inputs.environment }}

      - name: "Promote artefacts"
        run: make -f python-service.mk ${{ inputs.artefact_promotion_type }}
        working-directory: scripts/services
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          REPO_NAME: ${{ inputs.repo_name }}
          RELEASE_TAG: ${{ inputs.release_tag }}
          PRERELEASE_TAG: ${{ inputs.prerelease_tag }}
          WORKSPACE: ${{ inputs.workspace }} # TEMP
