name: Promote artefacts workflow
run-name: Promote ${{ inputs.type }} - ${{ inputs.name }} artefacts

permissions:
  id-token: write
  contents: read
on:
  workflow_call:
    inputs:
      build_type:
        description: "The type of project to build (service, package)"
        required: true
        type: string
      environment:
        description: "The deployment environment"
        required: true
        type: string
        default: "mgmt"
      name:
        description: "The name of the package to build"
        required: true
        type: string
      repo_name:
        description: "The name of the Git repo"
        required: true
        type: string
      artefact_promotion_type:
        description: "The type of artefact promotion to perform"
        required: true
        type: string
      type:
        description: "The type of permissions (e.g., account, app)"
        required: true
        type: string
      release_tag:
        description: "The release tag for the artefact"
        required: false
        type: string
      prerelease_tag:
        description: "The prerelease tag for the artefact"
        required: false
        type: string

jobs:
  promote-artefacts:
    name: "Promote ${{ inputs.type }} - ${{ inputs.name }} artefacts"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Configure AWS Credentials"
        uses: ./.github/actions/configure-credentials
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}
          type: ${{ inputs.type }}
          environment: ${{ inputs.environment }}

      - name: "Get directories"
        id: get-directories
        run: |
          if [[ "${{ inputs.build_type }}" == "service" ]]; then
            echo "working_directory=services/${{ inputs.name }}" >> $GITHUB_OUTPUT
            echo "build_directory=build/services/${{ inputs.name }}" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.build_type }}" == "package" ]]; then
            echo "working_directory=application/packages/${{ inputs.name }}" >> $GITHUB_OUTPUT
            echo "build_directory=build/packages/${{ inputs.name }}" >> $GITHUB_OUTPUT
          else
            echo "Invalid build type: ${{ inputs.build_type }}"
            exit 1
          fi

      - name: "Promote artefacts"
        run: make ${{ inputs.artefact_promotion_type }}
        working-directory: ${{ steps.get-directories.outputs.working_directory }}
        env:
          SERVICE: ${{ inputs.name }}
          PACKAGE: ${{ inputs.name }}
          REPO_NAME: ${{ inputs.repo_name }}
          RELEASE_TAG: ${{ inputs.release_tag }}
          PRERELEASE_TAG: ${{ inputs.prerelease_tag }}
