on: [push]

jobs:
  publish-nfrs-to-confluence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish@v1
        with:
          confluenceBaseUrl: ${{ secrets.CONFLUENCE_BASE_URL }}
          confluenceParentId: 1222133740
          atlassianUserName: ${{ secrets.ATLASSIAN_USERNAME }}
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
