on: [push]

jobs:
  publish-nfrs-to-confluence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: axro-gmbh/markdown-to-confluence-sync@1.4
        with:
          input_directory: docs/nfrs
          # exclude_files: this.md,that.md
          cloud: nhsd-confluence.digital.nhs.uk
          space_key: FRS
          parent_page_id: 1222133740
          user: ${{ secrets.ATLASSIAN_USERNAME }}
          token: ${{ secrets.ATLASSIAN_API_TOKEN }}