on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cupcakearmy/confluence-markdown-sync@v1
        with:
          from: 'docs/nfrs/nfr-by-domain.md' # The markdown file to publish
          to: '1247790797' # The confluence page id where to write the output
          cloud: https://nhsd-confluence.digital.nhs.uk/
          user: ${{ secrets.ATLASSIAN_USERNAME }}
          token: ${{ secrets.ATLASSIAN_API_TOKEN }}
